# This is a basic workflow to help you get started with Actions

name: My LaTeX CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          docker_image: ghcr.io/xu-cheng/texlive-small:latest
          prec_compile: |
            tlmgr update --self &&
            tlmgr install wrapfig enumitem titlesec svg phys biblatex-phys \
            tocbibind siunitx cleveref transparent graphbox
      - uses: actions/upload-artifact@v4
        with:
          name: my-thesis
          path: main.pdf
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          make_latest: true
          generate_release_notes: true
          files: |
            main.pdf
    permissions:
      contents: write
